{{- define "app.ollama.hpa" -}}
{{- $component := .component -}}
{{- $values := index .Values $component -}}
{{- if $values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}-{{ $component }}
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "ollama") | nindent 4 }}
    app.kubernetes.io/component: "{{ $component }}"
spec:
  maxReplicas: {{ $values.hpa.maxReplicas }}
  minReplicas: {{ $values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}-{{ $component }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $values.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $values.hpa.targetCPUUtilizationPercentage }}
{{- end -}}
{{- end -}}
