{{- define "app.redis.configMap" -}}
{{- $component := .component -}}
{{- $values := index .Values $component -}}
{{- $memoryLimitBytes := include "SI-to-bytes" $values.resources.limits.memory | int64 -}}
{{- $memoryLimitThresholdPercent := 0.8 -}}
{{- $memoryLimitBytes := mulf $memoryLimitBytes $memoryLimitThresholdPercent | int64 -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-{{ $component }}-config
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" $component) | nindent 4 }}
data:
  redis.conf: |
    {{- tpl (.Files.Get "files/redis/redis.conf.tpl") (dict "memoryLimitBytes" $memoryLimitBytes) | nindent 4 }}
{{- end -}}
