{{- $memoryLimitBytes := include "SI-to-bytes" .Values.redis.resources.limits.memory | int64 -}}
{{- $memoryLimitThresholdPercent := 0.8 -}}
{{- $memoryLimitBytes := mulf $memoryLimitBytes $memoryLimitThresholdPercent | int64 -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-redis-config
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "redis") | nindent 4 }}
data:
  redis.conf: |
    {{- tpl (.Files.Get "files/redis/redis.conf.tpl") (dict "memoryLimitBytes" $memoryLimitBytes) | nindent 4 }}