{{- $redisMemoryLimitBytes := include "SI-to-bytes" .Values.redis.resources.limits.memory | int64 -}}
{{- $pvcStorageMultiplier := 4 -}}
{{- $pvcStorageBytes := mulf $redisMemoryLimitBytes $pvcStorageMultiplier | int64 -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}-redis
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "redis") | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "app.fullname" . }}-redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-redis
        {{- include "app.labels.custom" (dict "context" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.image.registry }}/{{ .Values.redis.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              readOnly: true
              subPath: redis.conf
            - mountPath: /data
              name: redis
          {{- if .Values.redis.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli ping
            initialDelaySeconds: {{ default 0 .Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 20 .Values.redis.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ default 10 .Values.redis.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 .Values.redis.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.redis.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli ping
            initialDelaySeconds: {{ default 0 .Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 20 .Values.redis.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ default 10 .Values.redis.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ default 6 .Values.redis.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.redis.resources }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "app.fullname" . }}-redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - {{ default "ReadWriteOnce" (dig "pvc" "accessModes" "" .Values.redis) | quote }}
        resources:
            requests:
              storage: {{ printf "%d" $pvcStorageBytes }}
        {{- if and .Values.redis.pvc .Values.redis.pvc.storageClass }}
        storageClassName: {{ .Values.redis.pvc.storageClass }}
        {{- end }}
