fluentd:
  enabled: false

prometheus:
  customLabels:
    pulse/enabled: true
  collectClusterMetrics: false

elasticsearch:
  replicaCount: 3
  shardsCount: 3
  shardsReplicasCount: 1
  config:
    cluster:
      routing:
        allocation:
          disk:
            threshold_enabled: true
