{{- if and .Values.redisinsight.enabled .Values.redisinsight.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-redisinsight
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "redisinsight") | nindent 4 }}
    app.kubernetes.io/component: redisinsight
  annotations:
    {{- toYaml .Values.redisinsight.ingress.annotations | nindent 4 }}
    {{- if .Values.certificate.requireClientCert }}
    traefik.ingress.kubernetes.io/router.tls.options: {{ .Release.Namespace }}-{{ include "app.fullname" . }}-mtls@kubernetescrd
    {{- end }}
spec:
  ingressClassName: {{ .Values.redisinsight.ingress.className }}
  rules:
    - host: redisinsight.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}-redisinsight
                port:
                  number: {{ .Values.redisinsight.service.port }}
  {{- if .Values.redisinsight.ingress.tls.enabled }}
  tls:
    - secretName: {{ include "app.fullname" . }}-certificate
      hosts:
        - redisinsight.{{ .Values.domain }}
  {{- end }}
{{- end }}
